
CREATE TABLE DICT_FIO (
  ID INTEGER NOT NULL PRIMARY KEY,
  NFULL VARCHAR(150) NOT NULL,
  NFIRST VARCHAR(40) NOT NULL,
  NMIDDLE VARCHAR(40) NOT NULL,
  NLAST VARCHAR(40) NOT NULL,
  NSEX CHAR(1) NOT NULL
);

INSERT INTO DICT_FIO 
  SELECT ID, NFULL, NFIRST, NMIDDLE, NLAST, 
  CAST('M' AS CHAR(1)) AS NSEX 
  FROM DICT_FIO_MALE;

INSERT INTO DICT_FIO 
  SELECT ID + 10000000, NFULL, NFIRST, NMIDDLE, NLAST, 
  CAST('F' AS CHAR(1)) AS NSEX 
  FROM DICT_FIO_FEMALE;
